# Generated by Django 4.2.5 on 2023-10-01 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images', verbose_name='Image')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
            options={
                'verbose_name': 'RoomImage',
                'verbose_name_plural': 'RoomImages',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ManyToManyField(related_name='rooms', to='rooms.roomimage'),
        ),
    ]
